/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.eam.avanzada1.vistas;

import co.edu.eam.avanzada1.controladores.ControladorEstadoBloqueoUsuarios;
import co.edu.eam.avanzada1.entidades.Director;
import co.edu.eam.avanzada1.entidades.Docente;
import co.edu.eam.avanzada1.entidades.Estudiante;
import co.edu.eam.avanzada1.entidades.Persona;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Se quiere Se puede
 */
public class VentanaEstadoBloqueoUsuarios extends javax.swing.JInternalFrame {

    private ControladorEstadoBloqueoUsuarios controlador;

    /**
     * Creates new form VentanaEstadoBloqueoUsuarios
     */
    public VentanaEstadoBloqueoUsuarios() {
        initComponents();
        this.controlador = new ControladorEstadoBloqueoUsuarios();
        setVisible(true);
        setResizable(false);
        setClosable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLTitulo = new javax.swing.JLabel();
        jTFFiltroBusqueda = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTUsuarios = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        jLTitulo.setText("Filtro de busqueda:");

        jTFFiltroBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFFiltroBusquedaKeyReleased(evt);
            }
        });

        jTUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Identificación", "Cargo", "Nombre", "Apellido", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTUsuariosMouseClicked(evt);
            }
        });
        jTUsuarios.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTUsuariosKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTUsuarios);

        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLTitulo)
                            .addComponent(jTFFiltroBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLTitulo)
                .addGap(11, 11, 11)
                .addComponent(jTFFiltroBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFFiltroBusquedaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFFiltroBusquedaKeyReleased
        listarUsuariosNoRegistrados(jTFFiltroBusqueda.getText());
    }//GEN-LAST:event_jTFFiltroBusquedaKeyReleased

    private void jTUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTUsuariosMouseClicked
        int fila = jTUsuarios.getSelectedRow();
        String estado = (String) jTUsuarios.getValueAt(fila, 4);
        ponerNombreBoton(estado);
    }//GEN-LAST:event_jTUsuariosMouseClicked

    private void jTUsuariosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTUsuariosKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            int fila = jTUsuarios.getSelectedRow();
            String estado;
            if (fila == jTUsuarios.getRowCount() - 1) {
                estado = (String) jTUsuarios.getValueAt(fila, 4);                
            }else{
                estado = (String) jTUsuarios.getValueAt(fila+1, 4);
            }
            ponerNombreBoton(estado);
        }
        if (evt.getKeyCode() == KeyEvent.VK_UP) {
            int fila = jTUsuarios.getSelectedRow();
            String estado;
            if (fila == 0) {
                estado = (String) jTUsuarios.getValueAt(fila, 4);                
            }else{
                estado = (String) jTUsuarios.getValueAt(fila-1, 4);
            }
            ponerNombreBoton(estado);
        }
    }//GEN-LAST:event_jTUsuariosKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
    }//GEN-LAST:event_jButton1ActionPerformed

    public void ponerNombreBoton(String estado) {
        switch (estado) {
            case "Bloqueado":
                jButton1.setText("Desbloquear");
                break;
            case "Desbloqueado":
                jButton1.setText("Bloquear");
                break;
        }
    }

    public void listarUsuariosNoRegistrados(String parametro) {
        try {
            List<Persona> usuarios = controlador.listarUsuarioRegistrados(parametro);
            DefaultTableModel tabla = (DefaultTableModel) jTUsuarios.getModel();
            tabla.setRowCount(0);
            for (Persona usuario : usuarios) {
                Object[] fila = new Object[5];
                fila[0] = usuario.getNumeroDocumento();
                fila[2] = usuario.getNombre();
                fila[3] = usuario.getApellido();
                if (usuario instanceof Estudiante) {
                    fila[1] = "Estudiante";
                } else if (usuario instanceof Docente) {
                    fila[1] = "Docente";
                } else if (usuario instanceof Director) {
                    fila[1] = "Director";
                }
                if (usuario.isBloqueado()) {
                    fila[4] = "Bloqueado";
                } else {
                    fila[4] = "Desbloqueado";
                }
                tabla.addRow(fila);
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLTitulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFFiltroBusqueda;
    private javax.swing.JTable jTUsuarios;
    // End of variables declaration//GEN-END:variables
}
