/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.eam.avanzada1.vistas;

import co.edu.eam.avanzada1.controladores.ControladorCrearUsuarios;
import co.edu.eam.avanzada1.entidades.Director;
import co.edu.eam.avanzada1.entidades.Docente;
import co.edu.eam.avanzada1.entidades.Estudiante;
import co.edu.eam.avanzada1.entidades.Persona;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Se quiere Se puede
 */
public class VentanaCrerarUsuarios extends javax.swing.JInternalFrame {

    private ControladorCrearUsuarios controlador;

    /**
     * Creates new form VentanaCrerarEliminarUsuarios
     */
    public VentanaCrerarUsuarios() {
        initComponents();
        this.controlador = new ControladorCrearUsuarios();
        setVisible(true);
        setResizable(false);
        setClosable(true);
        setIconifiable(true);
        setBounds(0, 6, 492, 340);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTUsuarios = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTFFiltroBusqueda = new javax.swing.JTextField();
        jBCrear = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPFClave = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        jLIdUsuario = new javax.swing.JLabel();
        jBContinuar = new javax.swing.JButton();
        jBCancelar = new javax.swing.JButton();

        setTitle("Crear Usuarios");

        jTUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Identificación", "Cargo", "Nombre", "Apellido"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTUsuarios);

        jLabel1.setText("Filtro de busqueda:");

        jTFFiltroBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFFiltroBusquedaKeyReleased(evt);
            }
        });

        jBCrear.setText("CREAR");
        jBCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCrearActionPerformed(evt);
            }
        });

        jLabel8.setText("Contraseña:");

        jLabel9.setText("Identificación:");

        jBContinuar.setText("CONTINUAR");
        jBContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBContinuarActionPerformed(evt);
            }
        });

        jBCancelar.setText("CANCELAR");
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(48, 48, 48)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLIdUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                            .addComponent(jPFClave)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jBContinuar)
                        .addGap(62, 62, 62)
                        .addComponent(jBCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(jLIdUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPFClave, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBContinuar)
                    .addComponent(jBCancelar))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jTFFiltroBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jBCrear))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addGap(11, 11, 11)
                .addComponent(jTFFiltroBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jBCrear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCrearActionPerformed
        if (jTUsuarios.getSelectedRow() >= 0) {
            setBounds(0, 6, 492, 515);
            jLIdUsuario.setText(jTUsuarios.getValueAt(jTUsuarios.getSelectedRow(), 0) + "");
            jBCrear.setEnabled(false);
            jTFFiltroBusqueda.setEditable(false);
            jTUsuarios.setEnabled(false);
        }
    }//GEN-LAST:event_jBCrearActionPerformed

    private void jTFFiltroBusquedaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFFiltroBusquedaKeyReleased
        listarUsuariosNoRegistrados(jTFFiltroBusqueda.getText());
    }//GEN-LAST:event_jTFFiltroBusquedaKeyReleased

    private void jBContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBContinuarActionPerformed
        try {
            String clave = new String(jPFClave.getPassword());
            if (clave.length() >= 6) {
                controlador.crearUsuario(Long.parseLong(jLIdUsuario.getText()),
                        clave);
                setBounds(0, 6, 492, 340);
                jBCrear.setEnabled(true);
                jTFFiltroBusqueda.setEditable(true);
                jTUsuarios.setEnabled(true);
                jLIdUsuario.setText("");
                jPFClave.setText("");
                jTFFiltroBusqueda.setText("");
                listarUsuariosNoRegistrados("");
            } else {
                JOptionPane.showMessageDialog(null, "La clave debe ser mayor a 5 caracteres");
                jPFClave.setText("");
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jBContinuarActionPerformed

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        setBounds(0, 6, 492, 340);
        jBCrear.setEnabled(true);
        jTFFiltroBusqueda.setEditable(true);
        jTUsuarios.setEnabled(true);
        jLIdUsuario.setText("");
        jPFClave.setText("");
        jTFFiltroBusqueda.setText("");
    }//GEN-LAST:event_jBCancelarActionPerformed

    public void listarUsuariosNoRegistrados(String parametro) {
        try {
            List<Persona> usuarios = controlador.listarUsuarioNoRegistrados(parametro);
            DefaultTableModel tabla = (DefaultTableModel) jTUsuarios.getModel();
            tabla.setRowCount(0);
            for (Persona usuario : usuarios) {
                Object[] fila = new Object[4];
                fila[0] = usuario.getNumeroDocumento();
                fila[2] = usuario.getNombre();
                fila[3] = usuario.getApellido();
                if (usuario instanceof Estudiante) {
                    fila[1] = "Estudiante";
                } else if (usuario instanceof Docente) {
                    fila[1] = "Docente";
                } else if (usuario instanceof Director) {
                    fila[1] = "Director";
                }
                tabla.addRow(fila);
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBContinuar;
    private javax.swing.JButton jBCrear;
    private javax.swing.JLabel jLIdUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPFClave;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFFiltroBusqueda;
    private javax.swing.JTable jTUsuarios;
    // End of variables declaration//GEN-END:variables
}
