/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.eam.avanzada1.vistas;

import co.edu.eam.avanzada1.controladores.ControladorListaUsuarios;
import co.edu.eam.avanzada1.entidades.Director;
import co.edu.eam.avanzada1.entidades.Docente;
import co.edu.eam.avanzada1.entidades.Estudiante;
import co.edu.eam.avanzada1.entidades.Persona;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Se quiere Se puede
 */
public class VentanaListaUsuarios extends javax.swing.JInternalFrame {

    private ControladorListaUsuarios controlador;
    private static final String BLOQUEADO = "Bloqueado";
    private static final String DESBLOQUEADO = "Desbloqueado";
    private static final String DESBLOQUEAR = "Desbloquear";
    private static final String BLOQUEAR = "Bloquear";

    /**
     * Creates new form VentanaEstadoBloqueoUsuarios
     */
    public VentanaListaUsuarios() {
        initComponents();
        this.controlador = new ControladorListaUsuarios();
        setVisible(true);
        setResizable(false);
        setClosable(true);
        setIconifiable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLTitulo = new javax.swing.JLabel();
        jTFFiltroBusqueda = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTUsuarios = new javax.swing.JTable();

        setTitle("Lista Usuarios");

        jLTitulo.setText("Filtro de busqueda:");

        jTFFiltroBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFFiltroBusquedaKeyReleased(evt);
            }
        });

        jTUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Identificación", "Cargo", "Nombre", "Apellido", "Correo Elec", "Telefono", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTUsuarios);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 682, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLTitulo)
                            .addComponent(jTFFiltroBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLTitulo)
                .addGap(11, 11, 11)
                .addComponent(jTFFiltroBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFFiltroBusquedaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFFiltroBusquedaKeyReleased
        listarUsuariosRegistrados(jTFFiltroBusqueda.getText());
    }//GEN-LAST:event_jTFFiltroBusquedaKeyReleased

    public void listarUsuariosRegistrados(String parametro) {
        try {
            List<Persona> usuarios = controlador.listarUsuarioRegistrados(parametro);
            DefaultTableModel tabla = (DefaultTableModel) jTUsuarios.getModel();
            tabla.setRowCount(0);
            for (Persona usuario : usuarios) {
                Object[] fila = new Object[7];
                fila[0] = usuario.getNumeroDocumento();
                fila[2] = usuario.getNombre();
                fila[3] = usuario.getApellido();
                fila[4] = usuario.getCorreo();
                fila[5] = usuario.getTelefono();
                if (usuario instanceof Estudiante) {
                    fila[1] = "Estudiante";
                } else if (usuario instanceof Docente) {
                    fila[1] = "Docente";
                } else if (usuario instanceof Director) {
                    fila[1] = "Director";
                }
                if (usuario.isBloqueado()) {
                    fila[6] = BLOQUEADO;
                } else {
                    fila[6] = DESBLOQUEADO;
                }
                tabla.addRow(fila);
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLTitulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFFiltroBusqueda;
    private javax.swing.JTable jTUsuarios;
    // End of variables declaration//GEN-END:variables
}
